services:
  todo-app:
    build: .
    container_name: todo-app # This MUST match the name in the Caddyfile
    restart: unless-stopped
    networks:
      - caddy_mesh

networks:
  caddy_mesh:
    external: true